-- MySQL Script generated by MySQL Workbench
-- qua 14 abr 2021 21:11:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Introducao_MER
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Introducao_MER
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Introducao_MER` ;
USE `Introducao_MER` ;

-- -----------------------------------------------------
-- Table `Introducao_MER`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Introducao_MER`.`cargos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_cargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Introducao_MER`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Introducao_MER`.`funcionarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `telefone` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `id_cargos` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_funcionarios_1_idx` (`id_cargos` ASC) VISIBLE,
  CONSTRAINT `fk_funcionarios_1`
    FOREIGN KEY (`id_cargos`)
    REFERENCES `Introducao_MER`.`cargos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
